apiVersion: batch/v1
kind: Job
metadata:
  name: elt-pipeline
spec:
  template:
    spec:
      containers:
        - name: elt
          image: elt-orchestrator:latest
          envFrom:
            - secretRef:
                name: db-credentials
      restartPolicy: Never
